Добавляет имя наставника
htmlacademy-adaptive/2008437-sedona-27 pull request #1
Opened 2022-11-23 18:43 UTC by Vyachowski

2022-11-24 08:27 UTC, babtshe requested changes

2022-11-24 08:27 UTC, babtshe commented on Readme.md
> +* Наставник: `Александр Бабченко`.
Хорошо бы добавить ссылку на профиль по аналогии со строкой выше.

2022-11-24 17:32 UTC, Vyachowski commented on Readme.md
> +* Наставник: `Александр Бабченко`.
Готово.

2022-11-25 07:03 UTC, babtshe approved these changes

2022-11-25 07:03 UTC, merged