HTML разметка трех страниц
htmlacademy-adaptive/2008437-sedona-27 pull request #2
Opened 2023-01-03 14:22 UTC by Vyachowski

2023-01-09 08:04 UTC, babtshe requested changes

2023-01-09 08:04 UTC, babtshe commented on source/catalog.html
> +      <a class="main-header__logo" href="#">
ссылку на главную хорошо бы добавить
Кроме того, элемент `main-header__logo` есть, а сам блок не встречается

2023-01-09 08:04 UTC, babtshe commented on source/catalog.html
> +            <li class="site-list__item--current">
в каталоге активная ссылка другая же

2023-01-09 08:04 UTC, babtshe commented on source/catalog.html
> +              <a class="site-list__link" href="#">Фото и видео</a>
тут `href` можно убрать, страница не должна ссылаться сама на себя

2023-01-09 08:04 UTC, babtshe commented on source/catalog.html
> +      <section class="promo catalog-promo">
точно тут нужно сразу два блока?

2023-01-09 08:04 UTC, babtshe commented on source/catalog.html
> +        <video class="vide-presentation__video" poster="img/video-cover.jpg">
❗️

2023-01-09 08:04 UTC, babtshe commented on source/catalog.html
> +    <footer class="catalog-footer footer">
❗️

2023-01-09 08:04 UTC, babtshe commented on source/form.html
> +        <form class="review-form__form" action="https://echo.htmlacademy.ru/" method="get">
стоит посмотреть в доке про отличия методов формы. В данном случае лучше использовать POST

2023-01-09 08:04 UTC, babtshe commented on source/form.html
> +              <input class="review-form__field field field--name" type="text" placeholder="Пётр" aria-label="Поле ввода имени.">
обязательные поля было бы правильно обозначить соответствующим атрибутом, и `name` забыл добавить

2023-01-09 08:04 UTC, babtshe commented on source/form.html
> +              <input class="review-form__field field field--phone" type="number" placeholder="Введите телефон" aria-label="Поле ввода телефона.">
для телефона есть отдельный тип

2023-01-09 08:04 UTC, babtshe commented on source/form.html
> +            <legend class="review-form__title">ВАше Общее впечатление:</legend>
❗️

2023-01-09 08:04 UTC, babtshe commented on source/form.html
> +            <textarea class="review-form__textarea" name="review-text" id="textarea_form" cols="30" rows="10">Опишите подробно все свои восторги
это плейсхолдер, а не содержимое инпута.

2023-01-09 08:04 UTC, babtshe commented on source/form.html
> +        </form>
кнопка для отправки формы потерялась

2023-01-09 08:04 UTC, babtshe commented on source/index.html
> +              <li class="features__sublist__item">
обрати внимание на синтаксис названий классов по БЭМ

2023-01-09 08:04 UTC, babtshe commented on source/index.html
> +              <h3 class="features__title">НЕБОЛЬШАЯ ПЛОЩАДЬ</h3>
Прописные буквы задаются в стилях, а не в разметке. Это удобно, так как избавляет от необходимости переписывать тексты для смены отображения.

2023-01-09 14:41 UTC, Vyachowski commented on source/index.html
> +              <li class="features__sublist__item">
Да, понял о чем речь, абсолютно неправильное наименование.

2023-01-09 16:45 UTC, Vyachowski commented on source/form.html
> +            <legend class="review-form__title">ВАше Общее впечатление:</legend>
Здесь нужно поправить орфографию или я не замечаю какой-то ошибки?

2023-01-09 16:45 UTC, Vyachowski commented on source/index.html
> +              <li class="features__sublist__item">
Сделал новый вариант – так корректно именовать элементы блоков?

2023-01-09 16:45 UTC, Vyachowski commented on source/index.html
> +              <h3 class="features__title">НЕБОЛЬШАЯ ПЛОЩАДЬ</h3>
Поправил везде. Я просто копировал текст из макета, а он там странно вразнобой задан.

2023-01-09 21:15 UTC, babtshe commented on source/form.html
> +            <legend class="review-form__title">ВАше Общее впечатление:</legend>
текст

2023-01-11 09:10 UTC, babtshe approved these changes

2023-01-11 09:10 UTC, babtshe commented on source/catalog.html
> +        <span class="footer__hashtag">#visitsedona</span>
конкретно тут можно было оставить большие буквы. Маловероятно что размеры будут меняться, а для больших букв в части слова придётся добавлять отдельную обёртку, чтобы можно было через стили управлять.

2023-01-11 09:11 UTC, merged