Module5 task1
htmlacademy-adaptive/2008437-sedona-27 pull request #5
Opened 2023-01-19 22:35 UTC by Vyachowski

2023-01-21 16:19 UTC, babtshe requested changes

2023-01-21 16:19 UTC, babtshe commented on source/catalog.html
> +        <h2 class="visually-hidden">Пожалуй, лучший курорт Аризоны!</h2>
h2 не должен идти перед h1. А тут он ещё и скрытый. Чем обычный параграф не годится?

2023-01-21 16:19 UTC, babtshe commented on source/less/blocks/features-card.less
> +  background-color: @grey;
использовать текущее значение цвета в названии переменной не лучшая идея. Завтра серый превратится в белый, а переменная останется. Удачи тому, кто будет поддерживать проект в дальнейшем.

2023-01-21 16:19 UTC, babtshe commented on source/less/blocks/features-card.less
> +  & .features-card__title {
см [критерий](https://up.htmlacademy.ru/adaptive/27/criteries#d11)

2023-01-21 16:19 UTC, babtshe commented on source/less/blocks/review-form.less
> +}
❗️

2023-01-21 16:19 UTC, babtshe commented on source/less/variables.less
> +@transparent-white: fade(#ffffff, 30%);
см [критерий](https://up.htmlacademy.ru/adaptive/27/criteries#d8)

2023-01-21 17:25 UTC, Vyachowski commented on source/catalog.html
> +        <h2 class="visually-hidden">Пожалуй, лучший курорт Аризоны!</h2>
Тогда секция остается без заголовка, что как я понимаю недопустимо. Поменял их местами, в принципе это не принципиально в данном случае.

2023-01-21 18:02 UTC, Vyachowski commented on source/less/blocks/features-card.less
> +  background-color: @grey;
Добавил корректные именования и структуру всем переменным и миксерам

2023-01-21 18:31 UTC, Vyachowski commented on source/less/variables.less
> +@transparent-white: fade(#ffffff, 30%);
Исправил везде

2023-01-21 18:33 UTC, Vyachowski commented on source/less/blocks/review-form.less
> +}
Здесь не совсем понял в чем ошибка.

2023-01-21 20:48 UTC, Vyachowski commented on source/less/blocks/review-form.less
> +}
Понял :)

2023-01-23 08:36 UTC, babtshe commented on source/catalog.html
> +        <h2 class="visually-hidden">Пожалуй, лучший курорт Аризоны!</h2>
Секция не обязательно должна содержать заголовок каждый раз, см [доку](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section#using_a_section_without_a_heading)

2023-01-23 08:41 UTC, babtshe requested changes
тесты не проходят:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/30229773/213996960-7c23c204-48a8-43d2-b35f-45245ac8fa6e.png">

2023-01-23 08:41 UTC, babtshe commented on source/catalog.html
> +        <h2 class="promo__title promo__title--catalog">Фото и видео</h2>
прошлый заголовок был лучше по смыслу.

2023-01-23 08:41 UTC, babtshe commented on source/less/blocks/banner.less
> +  background-color: @menu-accent-color;
👍

2023-01-23 10:15 UTC, merged